spring.application.name=demaleProyect
spring.datasource.url=jdbc:mysql://localhost:3306/demaleProyect?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

apis.net.pe.dni.url=https://api.apis.net.pe/v1/dni
apis.net.pe.ruc.url=https://api.apis.net.pe/v1/ruc
apis.net.pe.token=apis-token-15878.jijDskYgfXtbVudkfPrXg5La70FNEGc7

factiliza.cee.url=https://api.factiliza.com/api/consulta/cee
factiliza.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODg4NyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC4wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImNvbnN1bHRvciJ9.st_EsCrXj7cloYsoKM9obWf9DVW0Fj_79mvWchrEVPo

spring.web.cors.allowed-origins=http://localhost:4200,http://localhost:13513
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600